// Serial Peripheral Interface
// Full-duplex transfer: Master shifts txData out on MOSI, simultaneously shifts MISO into rxData
// 8 bits, MSB-first

module spiMaster(
    input logic sys_clk,
    input logic sys_rst_n,

    input logic start,
    input logic [7:0] txData,
    output logic [7:0] rxData,
    output logic busy,
    output logic done,

    output logic sclk,  // Serial clock generated by this master
    output logic mosi,  // Master out, slave in
    input logic miso,   // Master in, slave out
    output logic cs_n   // Active-low chip select
);

    // Change to control SPI speed
    localparam int CLK_DIV = 4; // SCLK toggles every CLK_DIV sys_clk cycles
    // Full SCLK period = 2 * CLK_DIV sys_clk cycles

    typedef enum logic [1:0] {
        IDLE,
        TRANSFER,
        FINISH
    } spiState;

    spiState state;

    logic [$clog2(CLK_DIV)-1:0] clkCounter; // ceiling(log2(N): how many bits are needed to count up to N-1, parameter-friendly

    logic [7:0] txShift;
    logic [7:0] rxShift;
    logic [2:0] bitIndex;

    always_ff @(posedge sys_clk or negedge sys_rst_n) begin
        if (!sys_rst_n) begin
            state <= IDLE;

            clkCounter <= '0;
            txShift <= 8'd0;
            rxShift <= 8'd0;
            bitIndex <= 3'd0;

            rxData <= 8'd0;
            busy <= 1'b0;
            done <= 1'b0;

            sclk <= 1'b0;
            mosi <= 1'b0;
            cs_n <= 1'b1;
        end else begin
            done <= 1'b0;   // done is a one-clock pulse
            
            case (state)
                IDLE: begin
                    busy <= 1'b0;
                    sclk <= 1'b0;
                    cs_n <= 1'b1;
                    clkCounter <= '0;

                    if (start) begin
                        txShift <= txData;  // Load transmit shift register
                        rxShift <= 8'd0;    // Clear receive shift register

                        mosi <= txData[7];  // Start with MSB on MOSI before first rising edge
                        bitIndex <= 3'd7;

                        busy <= 1'b1;
                        cs_n <= 1'b0;
                        state <= TRANSFER;
                    end
                end

                TRANSFER: begin
                    busy <= 1'b1;
                    cs_n <= 1'b0;

                    if (clkCounter == CLK_DIV - 1) begin
                        clkCounter <= '0;
                        sclk <= ~sclk; // Toggle SPI clock

                        if (sclk == 1'b0) begin
                            // Runs when old sclk is low
                            // Nonblocking assignments update after the block, sclk is about to rise
                            // Mode 0 samples MISO on rising edge.
                            rxShift[bitIndex] <= miso;
                        end else begin
                            // Runs when old sclk is high, sclk is about to fall.
                            // Mode 0 changes MOSI on falling edge.
                            if (bitIndex == 3'd0) begin
                                state <= FINISH;
                            end else begin
                                bitIndex <= bitIndex - 1'b1;
                                mosi <= txShift[bitIndex - 1'b1];
                            end
                        end
                    end else begin
                        clkCounter <= clkCounter + 1'b1;
                    end
                end

                FINISH: begin
                    cs_n <= 1'b1;
                    sclk <= 1'b0;
                    busy <= 1'b0;

                    rxData <= rxShift; // Present received byte
                    done <= 1'b1; // One-clock completion pulse.

                    state <= IDLE;
                end

                default: begin
                    state <= IDLE;
                end
            endcase
        end
    end

endmodule