-d /home/erayacikgz/Desktop/fpga/1_LedBlink/build/1_LedBlink/impl/gwsynthesis/1_LedBlink.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/erayacikgz/Desktop/fpga/1_LedBlink/build/1_LedBlink/src/blink.cst
-cfg /home/erayacikgz/Desktop/fpga/1_LedBlink/build/1_LedBlink/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
