-d /home/erayacikgz/Desktop/fpga/8_QuadratureDecoder/quadratureDecoder/impl/gwsynthesis/quadratureDecoder.vg
-p GW1NR-9C-QFN88-6
-pn GW1NR-LV9QN88C6/I5
-cst /home/erayacikgz/Desktop/fpga/8_QuadratureDecoder/quadratureDecoder/src/tangnano9k.cst
-cfg /home/erayacikgz/Desktop/fpga/8_QuadratureDecoder/quadratureDecoder/impl/pnr/device.cfg
-sdc /home/erayacikgz/Desktop/fpga/8_QuadratureDecoder/quadratureDecoder/src/tangnano9k.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
